### ISSUE TITLE
FEAT: create dm at profile 

### ISSUE THREAD

**Issue by joonseong11** [Gaepo-transcendance-fighters/FRONT-END#104]
## 이전에 변경된 사항
- 초기 정책은 DM방을 생성하고 메세지를 보내야 서버에서도 방이 생성되는 것.
- 그러나 프론트의 상황적이유로 DM 방을 생성하기만 하면 서버에서도 방이 생기는 것으로 변경됨. (재킴님이 이유를 다시확인하고 싶다고함.)

## 구현하기 위해
- DM 하기를 누르면 서버에 방이 만들어 져야함.
  - 이미 방이 존재한다면 그 방으로 리디렉션.
  - 새로 방을 만든다면 새로운 방으로 리디렉션
    - 을 하려고 햇으나, 구조적 문제가 예상되어 DM 방만 생성하게 두고 직접 방을 눌러 참여하게 유도하려 함. (그렇다면 자동으로 dm 탭을 활성화 시켜주려고 한다.)
- DM 방이 생성되면 관련된 사람은 DM 방 목록이 동기화 되어야한다.
-> create_dm API에서 해결해야함. 
-> API 변경이 필요. (아래에 jujeon이 한번 수정요구한 emit API)</br> -> 그런데 이대로 하게되면 프론트에서 배열 요소하나하나마다 접근해서 나와 같은 idx인지 검사해야하고 맞는 요소들만 따로 빼내서 객체를 새로 만든다음에 전역상태관리로 들어가야한다. 비용이 크다.)
- create_dm 은 초기에 room_id 에 msg 와 관련된 내용들을 보내주었다. 그러나 이를 방에 소속된 두사람에게 따로따로 DM 채널리스트 정보 (chat_get_DMlist API 와 같은 형태) 를 보내주어야 한다. **`[지킴님 주전님 재킴님 세명이서 검토 필요]`**
 

```
// request body
{
	targetNickname : string,
	targetIdx : string,
	// msg : string 
        // msg는 필요가 없게 되었음. 어차피 방이생성됟고나면 직접 그 방을 눌러서 들어가게 되고 
        // 그러면 dm방 리스트를 통해 dm 방 입장 chat_get_DM 으로 처리하게 된다
}
```

```
// 원래 create_dm emit 
{
	message {
		sender : string, 
		msg : string,
                 msgDate : Date()
	},
	channelIdx : number,
}
```

```
// jujeon이 한번 수정 요구한 create_dm emit
{
	channelList[]? {
          channel {
		userIdx1 : number,
		userIdx2 : number,
		userNickname1 : string,
		userNickname2 : string,  
		channelIdx : number
                         }
}

```
 
 ``` 
// 최종적으로 필요한 create_dm (chat_get_DMlist API 와 같은 형태)
{
	channelList[]? {
    channel {
      owner?: null,
      targetNickname?: string
      channelIdx: number,
      mode : enum
    }
}
```

**Comment by jnkeniaem** [comment]
3번째 레츠거

**Comment by jnkeniaem** [comment]
dm하기 버튼 눌렀을때 이미 기존 방 있으면 서버에서 300보내서 프론트에서 chat_enter 쏴주고,
기존 방 없으면 200 보내서 방 생성
