### ISSUE TITLE
[QUESTION] bearer 는 https 에서만 동작합니다...!

### ISSUE THREAD

**Issue by joonseong11** [Gaepo-transcendance-fighters/FRONT-END#137]
[bearer token 참고자료](https://swagger.io/docs/specification/authentication/bearer-authentication/)

현재의 예상 구조는 nginx에 올리는것이 아닌 컨테이너에 바로 nextjs, nestjs 서버를 바로 올리기때문에 http 입니다!

**Comment by HiHoi** [comment]
<img width="765" alt="스크린샷 2023-09-10 오후 5 30 25" src="https://github.com/Gaepo-transcendance-fighters/FRONT-END/assets/54823522/5b0310a4-a577-4c67-abd4-21b8391e443a">
