### ISSUE TITLE
Send 버튼 누르면 자동으로 input 으로 포커싱 되는 기능이 mui 에서는 동작하지 않는다 해결필요

### ISSUE THREAD

**Issue by joonseong11** [Gaepo-transcendance-fighters/FRONT-END#140]

**Comment by HiHoi** [comment]
# MUI Form 이벤트에 한글이 들어가면 두번 호출되는 문제
https://junhyunny.github.io/react/typescript/korean-keyboard-event-error/

## 문제 상황
영어나 다른 언어는 댓글창에 잘 들어가지만, 한글만 유독 알람창과 동시에 마지막 값이 남는 일이 생겼습니다.

<img width="522" alt="스크린샷 2023-06-29 오후 7 37 44" src="https://github.com/peer-42seoul/mission-peerflow-FE/assets/54823522/a9af22f5-dfa9-46ea-966f-50b140a2947f">

## 이유
1. Composition event로 인해 생기는 일: html 이벤트와 web api 이벤트가 동시에 들어와서 생기는 일
2. MUI textField의 한글 처리 로직 오류: 거기에 한글 초기화 부분에서 값이 이상하게 남아서 이벤트가 작동

## 해결방안
onSubmit 이벤트에서 composition event의 호출을 막아버렸습니다.
더 정신 나간건 MUI인지 next.js인지 모르지만 composition 타입을 잡지 못해서 값이 없다고 뜨는데 실제로는 있습니다;;

```
if (e.nativeEvent.isComposing) return
```

### e.nativeEvent 구조체
<img width="522" alt="스크린샷 2023-06-29 오후 7 38 31" src="https://github.com/peer-42seoul/mission-peerflow-FE/assets/54823522/ccd34999-454b-4f9a-9935-5f17e004fa9f">
