### ISSUE TITLE
실시간 핫이슈

### ISSUE THREAD

**Issue by HiHoi** [Gaepo-transcendance-fighters/FRONT-END#151]
놀랍게도 뜨거운 이슈가 아니라 실시간 수정입니다.

**Comment by joonseong11** [comment]
- [x] 닉네임 수정이 되지 않는다.
- [x] 상대방 멤버 리스트에서 상대방 프로필에서dm 하기를 누르면 아무런 동작도 되지 않는다. 기존에 방이 있으면 리디렉션 되어야하고, 없으면 새로운 방이 만들어지고 하단에 알림이 떠야한다.
-
