### ISSUE TITLE
[기능명세코드추가] MAIN-CHAT-13 ~ 16

### ISSUE THREAD

**Issue by joonseong11** [Gaepo-transcendance-fighters/FRONT-END#18]
MAIN-CHAT-13 | 메인 | 채팅 | 메세지 전송 (+ 백엔드 통신)
MAIN-CHAT-14 | 메인 | 채팅 | 메시지 화면 출력
MAIN-CHAT-15 | 메인 | 채팅 | 채팅방 전환 기능 | chat list 랑 연계
MAIN-CHAT-16 | 메인 | 채팅 | 해당 dm 방 대화기록 불러오기

**Comment by HiHoi** [comment]
확인했습니다!
