### ISSUE TITLE
REFACTOR: Context API

### ISSUE THREAD

**Issue by HiHoi** [Gaepo-transcendance-fighters/FRONT-END#45]
## 확정

1. 방 목록과 방 참가 인원에 대한 전역 관리
2. 블락 리스트
4. 인게임에 대한 정보: 점수, 좌표, 딜레이 등등
5. 채팅창에 대한 정보: 채팅창 오픈 여부(state, setter)

**Comment by joonseong11** [comment]
현재 채팅창이 열려있는지 알 수 있는 state
showMembersList: boolean;
setShowMembersList: Dispatch<SetStateAction<boolean>>;
